# Generated by Django 4.1.3 on 2022-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=100)),
                ('agama', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('status_bantuan', models.CharField(max_length=100)),
            ],
        ),
    ]
