# Generated by Django 4.1.3 on 2022-11-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RukunTtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBantuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='agama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.agama'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='jenis_kelamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.jeniskelamin'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.rukunttg'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='status_bantuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.statusbantuan'),
        ),
    ]
