# Generated by Django 4.1.3 on 2022-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0002_agama_jeniskelamin_rukunttg_statusbantuan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_warga',
            old_name='tempat_lahir',
            new_name='tempat_tanggal_lahir',
        ),
        migrations.AlterField(
            model_name='rukunttg',
            name='nama',
            field=models.IntegerField(null=True),
        ),
    ]
