# Generated by Django 4.1.3 on 2022-11-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0003_rename_tempat_lahir_data_warga_tempat_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_warga',
            name='agama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.agama'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='jenis_kelamin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.jeniskelamin'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='rt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.rukunttg'),
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='status_bantuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.statusbantuan'),
        ),
    ]
