# Generated by Django 4.1.3 on 2022-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0004_alter_data_warga_agama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rukunttg',
            name='nama',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
