# Generated by Django 4.1.3 on 2022-11-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0005_alter_rukunttg_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rukunttg',
            name='nama',
            field=models.IntegerField(null=True),
        ),
    ]
