# Generated by Django 4.1.3 on 2022-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0006_alter_rukunttg_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_warga',
            name='rt',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='RukunTtg',
        ),
    ]
