# Generated by Django 4.1.3 on 2022-11-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0009_alter_data_warga_rt_delete_rukungttg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RukunTtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='data_warga',
            name='rt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendataan_warga.rukunttg'),
        ),
    ]
