# Generated by Django 4.1.3 on 2022-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendataan_warga', '0010_rukunttg_alter_data_warga_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_warga',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar/'),
        ),
        migrations.AddField(
            model_name='data_warga',
            name='tanggal_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
